# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='Bus No')),
                ('title', models.CharField(max_length=255, verbose_name='Bus Info')),
                ('latitude', models.CharField(max_length=255, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=255, verbose_name='Longitude')),
                ('is_public', models.BooleanField(default=True, verbose_name='Like My Service?')),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('date_updated', models.DateTimeField(verbose_name='date updated')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BusInfo', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'BusInfo',
                'verbose_name_plural': 'BusInfo',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='BusNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'BusNo',
                'verbose_name_plural': 'BusNos',
                'ordering': ['name'],
            },
        ),
    ]
